import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [aws, setAws] = useState("");
  const [links, setLinks] = useState([]);

  async function submitWebsiteURL() {
    const data = await fetch("/api/get-article-links", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        url: "https://bbc.com",
      }),
    }).then((res) => res.json());
    setAws(data.data);
    console.log(data.data);
  }

  const getAllLinks = () => {
    fetch(aws)
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        setLinks(data);
      });
  };

  useEffect(() => {
    submitWebsiteURL();
    getAllLinks();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Please click on link below :
        {links.map((link, index) => {
          return (
            <div key={index}>
              <a href={link}>{link}</a>
            </div>
          );
        })}
      </div>
    </div>
  );
}
