import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'


export default  function Home() {
const [websiteURL, setWebsiteURL] = useState('')
 async function submitWebsiteURL(){
   const data = await fetch('/api/get-article-links',{
     method: 'POST', 
     headers:{
       'Content-Type': 'application/json'
     },
     body: JSON.stringify({
       url:"https://bbc.com"
     })
   }).then((res)=>res.json())
// console.log(res)
 }


 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.inputArea}>
				<input
					type="text"
					value={websiteURL}
					onChange={(e) => setWebsiteURL(e.target.value)}
					placeholder="Enter a website URL"
				/>
				<button onClick={submitWebsiteURL}>Submit URL</button>
			</div>
    </div>
  )
}
