import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import storiesFile from "../stories.json";

export default function Home() {
  const [websiteURL, setWebsiteURL] = useState("");
  const [links, setLinks] = useState([]);

  async function submitWebsiteURL() {
    const data = await fetch("/api/get-article-links", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        url: "https://bbc.com",
      }),
    }).then((res) => res.json());
    setLinks(storiesFile);
  }

  useEffect(() => {
    submitWebsiteURL();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {links.map((link, index) => {
          return (
            <div key={index}>
              <p>{link}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
}